// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVvxwqmfMVu6i6GlDuD8HW4UQf87pafFc',
    appId: '1:784764792967:web:700fac98731545c9fb4822',
    messagingSenderId: '784764792967',
    projectId: 'shaundb-205b5',
    authDomain: 'shaundb-205b5.firebaseapp.com',
    storageBucket: 'shaundb-205b5.appspot.com',
    measurementId: 'G-FSB72BPT2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBLRCv4MjAwkZm_HhJQCLRf-TSIWTI4ZU',
    appId: '1:784764792967:android:98ce5a3b9ef2c6f5fb4822',
    messagingSenderId: '784764792967',
    projectId: 'shaundb-205b5',
    storageBucket: 'shaundb-205b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvGox37AB4lcBgXPz76-0I56hRwzxNVjw',
    appId: '1:784764792967:ios:7a0354f42073b06cfb4822',
    messagingSenderId: '784764792967',
    projectId: 'shaundb-205b5',
    storageBucket: 'shaundb-205b5.appspot.com',
    iosBundleId: 'com.example.resTourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvGox37AB4lcBgXPz76-0I56hRwzxNVjw',
    appId: '1:784764792967:ios:5df1c9e55c58953cfb4822',
    messagingSenderId: '784764792967',
    projectId: 'shaundb-205b5',
    storageBucket: 'shaundb-205b5.appspot.com',
    iosBundleId: 'com.example.resTourism.RunnerTests',
  );
}
